/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace PoviMartLib
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Customer : TBase
  {
    private int _NUMBER;
    private string _NAME;
    private string _EMAIL;
    private long _REGDATE;

    public int NUMBER
    {
      get
      {
        return _NUMBER;
      }
      set
      {
        __isset.NUMBER = true;
        this._NUMBER = value;
      }
    }

    public string NAME
    {
      get
      {
        return _NAME;
      }
      set
      {
        __isset.NAME = true;
        this._NAME = value;
      }
    }

    public string EMAIL
    {
      get
      {
        return _EMAIL;
      }
      set
      {
        __isset.EMAIL = true;
        this._EMAIL = value;
      }
    }

    public long REGDATE
    {
      get
      {
        return _REGDATE;
      }
      set
      {
        __isset.REGDATE = true;
        this._REGDATE = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool NUMBER;
      public bool NAME;
      public bool EMAIL;
      public bool REGDATE;
    }

    public Customer() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                NUMBER = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                NAME = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                EMAIL = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I64) {
                REGDATE = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Customer");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.NUMBER) {
          field.Name = "NUMBER";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(NUMBER);
          oprot.WriteFieldEnd();
        }
        if (NAME != null && __isset.NAME) {
          field.Name = "NAME";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(NAME);
          oprot.WriteFieldEnd();
        }
        if (EMAIL != null && __isset.EMAIL) {
          field.Name = "EMAIL";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(EMAIL);
          oprot.WriteFieldEnd();
        }
        if (__isset.REGDATE) {
          field.Name = "REGDATE";
          field.Type = TType.I64;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(REGDATE);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Customer(");
      bool __first = true;
      if (__isset.NUMBER) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NUMBER: ");
        __sb.Append(NUMBER);
      }
      if (NAME != null && __isset.NAME) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NAME: ");
        __sb.Append(NAME);
      }
      if (EMAIL != null && __isset.EMAIL) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("EMAIL: ");
        __sb.Append(EMAIL);
      }
      if (__isset.REGDATE) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("REGDATE: ");
        __sb.Append(REGDATE);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
